name: Run Renovate

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
