name: Run Renovate

on:
  workflow_dispatch:     # manual trigger
  schedule:
    - cron: '0 3 * * *'   # runs daily at 3 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
